console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = '#77C3B6'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    template = ' <#ffffff>on</> {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} <#EE7398>[✘]</>{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = "#E8ACDA"
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = '🌱 '
      branch_max_length = 25
      fetch_upstream_icon = true
      fetch_stash_count = true
      fetch_status = true
      cache_duration = 'none'
      commit_icon = '@'

  [[blocks.segments]]
    template = "<#ffffff>via</> \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
    foreground = "#F7DCA0"
    type = 'python'
    style = 'plain'

  [[blocks.segments]]
    template = "<#ffffff>via</> \ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    foreground = "#84DDCB"
    type = 'go'
    style = 'plain'

  [[blocks.segments]]
    template = "<#ffffff>via</> \ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    foreground = "#FC7208"
    type = 'rust'
    style = 'plain'

  [[blocks.segments]]
    template = "<#ffffff>via</> \ue620 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    foreground = "#77A3F8"
    type = 'lua'
    style = 'plain'

  [[blocks.segments]]
    template = "<#ffffff>via</> \uf308 {{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}} "
    foreground = "#316ce4"
    type = 'kubectl'
    style = 'plain'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
