session: local
attach: true

windows:
  - name: local
    root: ~/.config/nvim
    commands:
      - clear
  - name: Notes
    root: ~/Documents/Notes
    commands:
      - clear
  - name: Dev
    root: ~/dev/src/github.com/abzcoding/ctour
    selected: true
    commands:
      - export NVIM_OFFLINE=1
